### ISSUE TITLE
Can I add the implementation of a Trie data structure and functionalities like Search, Insert, Delete etc.

### ISSUE THREAD

**Issue by Rahul-Roy-21** [ishaangupta-YB/Hacktoberfest-2022#158]

**Comment by ishaangupta-YB** [comment]
Yes sure. Just don't forget to star this repo and add your name in [contributors](https://github.com/ishaangupta-YB/Hacktoberfest-2022/tree/main/contributors) folder

**Comment by Rahul-Roy-21** [comment]
@ishaangupta-YB, please help as I am unable to clone my forked repo, the error is as follows-

$ git clone https://github.com/Rahul-Roy-21/Hacktoberfest-2022_ishaangupta-YB.git
Cloning into 'Hacktoberfest-2022_ishaangupta-YB'...
remote: Enumerating objects: 1634, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 1634 (delta 54), reused 19 (delta 6), pack-reused 1525
Receiving objects: 100% (1634/1634), 91.40 MiB | 752.00 KiB/s, done.
Resolving deltas: 100% (579/579), done.
error: invalid path 'DSA/C++/Minimum and Maximum values of given expression with + and *.cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ishaangupta-YB** [comment]
> 

Rename the file "MinimumandMaximumvaluesofgivenexpression.cpp" instead of what you have done and then try.
But before that please fetch and update the repo.
@Rahul-Roy-21

**Comment by Rahul-Roy-21** [comment]
@ishaangupta-YB bro, I haven't created that file and this error is happening on cloning my forked copy of your repo.., I guess it can be solved if you can please change that filename

**Comment by ishaangupta-YB** [comment]
> @ishaangupta-YB bro, I haven't created that file and this error is happening on cloning my forked copy of your repo.., I guess it can be solved if you can please change that filename

Delete your forked repo. Clone it again and commit changes. Then make a new PR, this will resolve your issue.

**Comment by Rahul-Roy-21** [comment]
#

> > @ishaangupta-YB bro, I haven't created that file and this error is happening on cloning my forked copy of your repo.., I guess it can be solved if you can please change that filename
> 
> Delete your forked repo. Clone it again and commit changes. Then make a new PR, this will resolve your issue.

Forked your repo again, but still unable to clone it due to same reason. 
The file in your repo named -> 'DSA/C++/Minimum and Maximum values of given expression with + and *.cpp' is causing the problem.. 

### **Here is the Error**
$ git clone -c core.protectNTFS=false https://github.com/Rahul-Roy-21/Hacktoberfest-2022_ishaangupta-YB-.git
Cloning into 'Hacktoberfest-2022_ishaangupta-YB-'...
remote: Enumerating objects: 1830, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 1830 (delta 141), reused 193 (delta 74), pack-reused 1542
Receiving objects: 100% (1830/1830), 91.45 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (672/672), done.
error: unable to create file DSA/C++/Minimum and Maximum values of given expression with + and *.cpp: Invalid argument
Updating files: 100% (665/665), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ishaangupta-YB** [comment]
> > > @ishaangupta-YB bro, I haven't created that file and this error is happening on cloning my forked copy of your repo.., I guess it can be solved if you can please change that filename
> > 
> > 
> > Delete your forked repo. Clone it again and commit changes. Then make a new PR, this will resolve your issue.
> 
> Forked your repo again, but still unable to clone it due to same reason. The file in your repo named -> 'DSA/C++/Minimum and Maximum values of given expression with + and *.cpp' is causing the problem..
> 
> Even tried core.protectNTFS=false, it works but creates all your files after deleting them
> 
> ### **Here is the Error**
> $ git clone -c core.protectNTFS=false https://github.com/Rahul-Roy-21/Hacktoberfest-2022_ishaangupta-YB-.git Cloning into 'Hacktoberfest-2022_ishaangupta-YB-'... remote: Enumerating objects: 1830, done. remote: Counting objects: 100% (288/288), done. remote: Compressing objects: 100% (191/191), done. remote: Total 1830 (delta 141), reused 193 (delta 74), pack-reused 1542 Receiving objects: 100% (1830/1830), 91.45 MiB | 1.06 MiB/s, done. Resolving deltas: 100% (672/672), done. error: unable to create file DSA/C++/Minimum and Maximum values of given expression with + and *.cpp: Invalid argument Updating files: 100% (665/665), done. fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'



> > > @ishaangupta-YB bro, I haven't created that file and this error is happening on cloning my forked copy of your repo.., I guess it can be solved if you can please change that filename
> > 
> > 
> > Delete your forked repo. Clone it again and commit changes. Then make a new PR, this will resolve your issue.
> 
> Forked your repo again, but still unable to clone it due to same reason. The file in your repo named -> 'DSA/C++/Minimum and Maximum values of given expression with + and *.cpp' is causing the problem..
> 
> Even tried core.protectNTFS=false, it works but creates all your files after deleting them
> 
> ### **Here is the Error**
> $ git clone -c core.protectNTFS=false https://github.com/Rahul-Roy-21/Hacktoberfest-2022_ishaangupta-YB-.git Cloning into 'Hacktoberfest-2022_ishaangupta-YB-'... remote: Enumerating objects: 1830, done. remote: Counting objects: 100% (288/288), done. remote: Compressing objects: 100% (191/191), done. remote: Total 1830 (delta 141), reused 193 (delta 74), pack-reused 1542 Receiving objects: 100% (1830/1830), 91.45 MiB | 1.06 MiB/s, done. Resolving deltas: 100% (672/672), done. error: unable to create file DSA/C++/Minimum and Maximum values of given expression with + and *.cpp: Invalid argument Updating files: 100% (665/665), done. fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'


Try running this on your terminal/cmd:  git config --system core.longpaths true
Also i have changed the name of the file that might be causing error in your case. 
Try again and let me know :)

**Comment by Rahul-Roy-21** [comment]
Thanks bro, I have succesfully made a PR #233, please merge it with hacktoberfest-accepted tag.
