### ISSUE TITLE
Comment Section

### ISSUE THREAD

**Issue by AryanSahoo-2003** [ishaangupta-YB/Hacktoberfest-2022#199]
Hello! As I have seen many of my peers getting stuck at how to add comment section using php ..I want to create a sample website showing a basic comment section..
Can you assign it to me under Hactoberfest ?

**Comment by ishaangupta-YB** [comment]
> Hello! As I have seen many of my peers getting stuck at how to add comment section using php ..I want to create a sample website showing a basic comment section..
> Can you assign it to me under Hactoberfest ?

Yup. Go ahead.
Just don't forget to star this repo and add your name in the contributors folder!

**Comment by AryanSahoo-2003** [comment]
Hello!I have made the pull request..You can check it now..
My basic Interface looked like this..
![image](https://user-images.githubusercontent.com/110082824/194029854-a723c890-8451-4cf8-a963-04aa28214baa.png)
