### ISSUE TITLE
Firebase Authentication Project in React using ContextApi, Login via. Email Google Github.

### ISSUE THREAD

**Issue by Rahul-Roy-21** [ishaangupta-YB/Hacktoberfest-2022#283]
Hi @ishaangupta-YB, I wish to add a React Project that will demonstrate the use of React's ContextApi to provide user-specific AuthContext, the authentication being provided by Google's Firebase. This will have a simple Todoapp to display user-specific todos, data saved in/provided by Firebase Database. 

Please assign me with the appropriate tags of hacktoberfest-accepted..

**Comment by ishaangupta-YB** [comment]
> Hi @ishaangupta-YB, I wish to add a React Project that will demonstrate the use of React's ContextApi to provide user-specific AuthContext, the authentication being provided by Google's Firebase. This will have a simple Todoapp to display user-specific todos, data saved in/provided by Firebase Database. 
> 
> Please assign me with the appropriate tags of hacktoberfest-accepted..

Ok, go ahead.
