### ISSUE TITLE
> Fibonacci in python `n_terms = int(input ("How many terms the user wants to print? "))

### ISSUE THREAD

**Issue by ishaangupta-YB** [ishaangupta-YB/Hacktoberfest-2022#72]
> Fibonacci in python `n_terms = int(input ("How many terms the user wants to print? "))
> 
> # First two terms
> n_1 = 0 n_2 = 1 count = 0
> 
> # Now, we will check if the number of terms is valid or not
> if n_terms <= 0: print ("Please enter a positive integer, the given number is not valid")
> 
> # if there is only one term, it will return n_1
> elif n_terms == 1: print ("The Fibonacci sequence of the numbers up to", n_terms, ": ") print(n_1)
> 
> # Then we will generate Fibonacci sequence of number
> else: print ("The fibonacci sequence of the numbers is:") while count < n_terms: print(n_1) nth = n_1 + n_2 # At last, we will update values n_1 = n_2 n_2 = nth count += 1 `

@Daksheshapkare 
Add it as a python file in CP folder. Also add your name in contributors folder!

_Originally posted by @ishaangupta-YB in https://github.com/ishaangupta-YB/Hacktoberfest-2022/issues/63#issuecomment-1264321750_

You need to request for another PR so that i can merge

**Comment by SusavanMondal** [comment]
Hello, I am interested to solve this issue. Please assign it to me

**Comment by Daksheshapkare** [comment]
>         > Fibonacci in python `n_terms = int(input ("How many terms the user wants to print? "))
> > 
> > # First two terms
> > n_1 = 0 n_2 = 1 count = 0
> > 
> > # Now, we will check if the number of terms is valid or not
> > if n_terms <= 0: print ("Please enter a positive integer, the given number is not valid")
> > 
> > # if there is only one term, it will return n_1
> > elif n_terms == 1: print ("The Fibonacci sequence of the numbers up to", n_terms, ": ") print(n_1)
> > 
> > # Then we will generate Fibonacci sequence of number
> > else: print ("The fibonacci sequence of the numbers is:") while count < n_terms: print(n_1) nth = n_1 + n_2 # At last, we will update values n_1 = n_2 n_2 = nth count += 1 `
> 
> @Daksheshapkare 
> Add it as a python file in CP folder. Also add your name in contributors folder!
> 
> _Originally posted by @ishaangupta-YB in https://github.com/ishaangupta-YB/Hacktoberfest-2022/issues/63#issuecomment-1264321750_
> 
> 
> You need to request for another PR so that i can merge
>       


Actually I don't know how to do it
As I'm a new user of github 
Pls assign to anyone
