### ISSUE TITLE
Java Script Projects

### ISSUE THREAD

**Issue by pmihsan** [ishaangupta-YB/Hacktoberfest-2022#73]
Can we add javascript projects to web development

**Comment by ishaangupta-YB** [comment]
> Can we add javascript projects to web development

Yes you can. But don't forget to star this repo and add your name in contributors folder

**Comment by lognoroy** [comment]
Hey @ishaangupta-YB, I want to add project also , Please give a chance to improve this repo.

**Comment by ishaangupta-YB** [comment]
> Hey @ishaangupta-YB, I want to add project also , Please give a chance to improve this repo.

Hi @lognoroy . Yes you can add your project inside the Project directory. But don't forget to star this repo and add your name in contributors folder

**Comment by Eli4479** [comment]
i can add tic-tac-tao and quiz site.

**Comment by ishaangupta-YB** [comment]
> I can add tic-tac-tao and quiz site.
> Pls, assign it to me.

Ok go ahead. Just don't forget to star this repo and add your name in the contributors folder.
